### ISSUE TITLE
issue with binary:hinge

### ISSUE THREAD

**Issue by tuanvayn** [jpmml/jpmml-xgboost#45] opened 2019-12-05 04:02 UTC
I have xgb.Classifier() use binary:hinge in objective then build in this tools. but issue like that
![image](https://user-images.githubusercontent.com/22125166/70203185-ac127480-174e-11ea-8c5c-bccc8c8b414c.png)

**Comment by vruusmann** [comment] 2019-12-05 07:12
Closing as exact duplicate of #40

**Closed by vruusmann** 2019-12-05 07:12 UTC
