### ISSUE TITLE
spark+xgb+pipeline -> PMML file

### ISSUE THREAD

**Issue by leemoor** [jpmml/jpmml-xgboost#35] opened 2019-03-18 02:24 UTC
hi here is my model:
```
val XGBooster = new XGBoostClassifier(
      Map("eta" -> 0.05f,
        "max_depth" -> 8,
        "objective" -> "binary:logistic",
        "eval_metric" -> "auc",
        "baseScore" -> 0.6,
        "maxBin" -> 16,
        "num_round" -> 500,  
        "num_workers" -> 100
      )
    ).setFeaturesCol("features").setLabelCol("label")

    val pipeline = new Pipeline().setStages(Array(featureAssembler, XGBooster))
    val xgbmodel = pipeline.fit(train)

```
how can i use your jar to convert it to PMML ?  can i use it with a dependency way? 

both ways failed:
  ```
 val pmml = ConverterUtil.toPMMLByteArray(train.schema, xgbmodel)
    val pmml = new PMMLBuilder(train.schema, xgbmodel).buildByteArray()

```

and whats the difference with?:
https://github.com/jpmml/jpmml-sparkml-xgboost
thanks ,looking foward to your answer

**Comment by vruusmann** [comment] 2019-03-18 07:13
Duplicate of https://github.com/jpmml/jpmml-sparkml-xgboost/issues/10

**Closed by vruusmann** 2019-03-18 07:13 UTC
