### ISSUE TITLE
Model save in PMML using nyoka has different prediction result with xgboost model

### ISSUE THREAD

**Issue by Digbijaynk01** [jpmml/jpmml-xgboost#72] opened 2024-02-22 12:57 UTC
I am using nyoka package to generate the PMML file. nyoka version '5.5.0'.
use below pypmml package to load the model in my python code to do prediction.
What is observe there is huge difference in prediction result

Output of one row for cmparision;
PMML model prediction : Probabilti-0 : 0.142825, Probabilti-1 : 0.857175
same row prediction from model directly: Probabilti-0 : 0.516752, Probabilti-1 : 0.483248
I have checked non of feature have null value, exactly same data and same sequence of feature also used for prediction.

**Comment by vruusmann** [comment] 2024-02-22 16:33
Closing as exact duplicate of https://github.com/jpmml/jpmml-xgboost/issues/71

@Digbijaynk01 You're now blocked for spamming

**Closed by vruusmann** 2024-02-22 16:33 UTC
